FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./

ARG NODE_ENV=development
RUN npm install

RUN npm install -g nodemon

COPY ./src ./src

EXPOSE 3000

CMD ["nodemon", "--legacy-watch", "src/index.js"]
