services:
  hayasedb:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: HayaseDB-api
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    pull_policy: build

  postgres:
    image: postgres:latest
    container_name: HayaseDB-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - hayasedb-db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    attach: false

  pgadmin:
    image: dpage/pgadmin4
    container_name: HayaseDB-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    attach: false

  redis:
    image: redis:alpine
    container_name: HayaseDB-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  hayasedb-db:
  pgadmin-data:
  redis-data:


