services:
  hayasedb:
    container_name: HayaseDB-dev
    restart: always
    build:
      context: .
      args:
        NODE_ENV: development
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - database
    pull_policy: build

  database:
    container_name: HayaseDB-database
    image: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    attach: false
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@hayasedb.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - '5050:80'
    depends_on:
      - database
    attach: false
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  database_data:
  pgadmin-data:
