
services:
  hayasedb:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: HayaseDB-dev
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - API_URL=${API_URL}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - /app/node_modules
    pull_policy: build

  postgres:
    image: postgres:latest
    container_name: HayaseDB-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - hayasedb-db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    attach: false

volumes:
  hayasedb-db:
