
services:
  hayasedb:
    container_name: HayaseDB-api
    restart: always
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    labels:
      - "version=1.0.0"
      - "maintainer=info@hayasedb.com"
    environment:
      NODE_ENV: production
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      PORT: ${PORT}
      BASE_URL: ${BASE_URL}
      LOG_LEVEL: ${LOG_LEVEL}
      JWT_SECRET: ${JWT_SECRET}
      API_URL: ${API_URL}
    depends_on:
      - mongo
    pull_policy: build
  mongo:
    container_name: HayaseDB-db
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    attach: false

volumes:
  mongo-data:
