
services:
  hayasedb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: HayaseDB-prod
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    pull_policy: build

  postgres:
    image: postgres:latest
    container_name: HayaseDB-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - hayasedb-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    attach: false

volumes:
  hayasedb-db:
