services:
  app:
    container_name: hayasedb-api-api
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      APP_NODE_ENV: production
    env_file:
      - ../stack.env
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-hayasedb}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    restart: unless-stopped

volumes:
  postgres_data: