services:
  app:
    container_name: hayasedb-api-api
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      APP_NODE_ENV: production
    env_file:
      - ../stack.env
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on:
      - postgres
    networks:
      - hayasedb-api
    restart: unless-stopped

  postgres:
    container_name: hayasedb-api-postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-hayasedb}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    networks:
      - hayasedb-api
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data
    restart: unless-stopped

networks:
  hayasedb-api:
    driver: bridge

volumes:
  minio_data:
  postgres_data: